# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GYHandover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_img', models.ImageField(upload_to='./gyhandover/', verbose_name='附件图片')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'ordering': ['upload_time'],
            },
        ),
    ]
