# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170303_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='idNumber',
            new_name='employee_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telephoneNumber',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='usercode',
            new_name='telephone_number',
        ),
    ]
