# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IQCDataCVTE6486',
            fields=[
                ('scpi', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gwmc', models.CharField(max_length=100)),
                ('pzxcbh', models.CharField(max_length=100)),
                ('pzxcmc', models.CharField(max_length=100)),
                ('cssj', models.DateTimeField()),
            ],
        ),
    ]
