# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQCDataCVTE6486COPY',
            fields=[
                ('scpi', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gwmc', models.CharField(max_length=100)),
                ('pzxxbh', models.CharField(max_length=100)),
                ('pzxcmc', models.CharField(max_length=100)),
                ('cssj', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='iqcdatacvte6486',
            old_name='pzxcbh',
            new_name='pzxxbh',
        ),
    ]
