# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqc', '0002_auto_20170213_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iqcdatacvte6486',
            old_name='pzxcmc',
            new_name='pzxxmc',
        ),
        migrations.RenameField(
            model_name='iqcdatacvte6486copy',
            old_name='pzxcmc',
            new_name='pzxxmc',
        ),
    ]
