# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqc', '0004_auto_20170214_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqcdatacvte6486copy',
            name='tm',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
