# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqc', '0005_auto_20170214_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iqcdatacvte6486',
            old_name='scpi',
            new_name='scpc',
        ),
        migrations.RenameField(
            model_name='iqcdatacvte6486copy',
            old_name='scpi',
            new_name='scpc',
        ),
    ]
