# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqc', '0008_delete_iqcdatacvte6486copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQCDataCVTE6486COPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scpc', models.CharField(max_length=100, verbose_name='生成批次')),
                ('tm', models.CharField(max_length=100, unique=True, verbose_name='条码')),
                ('gwmc', models.CharField(max_length=100, verbose_name='工位名称')),
                ('pzxxbh', models.CharField(max_length=100, verbose_name='品质现象编号')),
                ('pzxxmc', models.CharField(max_length=100, verbose_name='品质现象名称')),
                ('cssj', models.DateTimeField(verbose_name='测试时间')),
            ],
        ),
    ]
