# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqc', '0009_iqcdatacvte6486copy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IQCDataCVTE6486',
        ),
    ]
