# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqc', '0012_iqcuploadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqcuploadrecord',
            name='upload_num',
            field=models.IntegerField(verbose_name='上传数量'),
        ),
    ]
