# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraDownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
            ],
        ),
        migrations.CreateModel(
            name='JiraSearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='姓名')),
                ('project_id', models.CharField(max_length=50, verbose_name='项目编号')),
                ('model', models.CharField(max_length=200, verbose_name='机型')),
                ('download_id', models.IntegerField(verbose_name='下载链接')),
                ('search_time', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
            ],
        ),
        migrations.AddField(
            model_name='jiradownloadrecord',
            name='search_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_record', to='jiradata.JiraSearchRecord'),
        ),
    ]
