# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jirasearchrecord',
            name='download_id',
            field=models.CharField(max_length=50, verbose_name='下载链接'),
        ),
    ]
